[package]
name = "Helloworldsampleenclave"
version = "0.9.8"
authors = ["Baidu"]

[lib]
name = "helloworldsampleenclave"
crate-type = ["staticlib"]

[features]
default = []

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_types = "0.9.8"
sgx_tstd = "0.9.8"
